stages:
  - deploy_backend
  - build_frontend

build_frontend:
  stage: build_frontend
  image: node:20  # Use a Node.js image
  script:
    - make exec  # Run the Makefile task for frontend build
  artifacts:
    paths:
      - frontend/dist # Define the path to the frontend build artifacts

deploy_backend:
  stage: deploy_backend
  script:
    - apt-get update
    - apt-get install -y ssh  # Install SSH client
    - mkdir -p ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa  # Use the secret variable
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-18-222-13-146.us-east-2.compute.amazonaws.com "cd /MetroPulse/backend && git fetch && git rebase && docker-compose up -d"
  only:
    - master
