stages:
  - deploy_backend
  - build_frontend
  - postman_tests

build_frontend:
  stage: build_frontend
  image: node:20  # Use a Node.js image
  allow_failure: true
  script:
    - make exec  # Run the Makefile task for frontend build
  artifacts:
    paths:
      - frontend/dist # Define the path to the frontend build artifacts

deploy_backend:
  stage: deploy_backend
  allow_failure: true
  script:
    - apt-get update
    - apt-get install -y ssh  # Install SSH client
    - mkdir -p ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa  # Use the secret variable
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-18-222-13-146.us-east-2.compute.amazonaws.com "cd /MetroPulse/backend && git pull && sudo docker stop $(sudo docker ps -aqf name=backend) && sudo docker build --tag backend --file ./Dockerfile . && sudo docker run -d --name metropulse --rm --network=host -i -t -v /home/ubuntu/MetroPulse/backend/:/usr/python backend"
  only:
    - fixed-main

postman_tests:
    stage: postman_tests
    image: 
        name: postman/newman:alpine
        entrypoint: [""]
    script:
        - cd backend
        - newman run postman_tests.json
